---
usuario: '{{ lookup("env", "SUDO_USER") }}'
usuario_home: "/home/{{ usuario }}"
usuario_config: "{{ usuario-home }}/.config"
super: '{{ lookup("env", "SUDO_USER") }}'
super_home: '{{ lookup("env", "HOME") }}'
super_config: "{{ super-home }}/.config"


