# https://copr.fedorainfracloud.org/coprs/frostyx/qtile/
- name: gui-qtile | qtile | Habilita repositório 'copr'
  community.general.copr:
    name: frostyx/qtile

# http://www.qtile.org
- name: gui-qtile | qtile | Instala TWM Qtile
  ansible.builtin.dnf:
    name:
      - qtile
      - qtile-extras

# https://copr.fedorainfracloud.org/coprs/jstanek/ports/
- name: gui-qtile | i3lock-color | Habilita repositório 'copr'
  community.general.copr:
    name: jstanek/ports

# https://github.com/Raymo111/i3lock-color
- name: gui-qtile | qtile | Instala pacote
  ansible.builtin.dnf:
    name:
      - i3lock-color     # required - i3lock with color functionality and other features
      - xdpyinfo          # required - prints basic diagnostic information about a given X server

- name: gui-qtile | i3lock-color | Remove repositório 'copr'
  community.general.copr:
    name: jstanek/ports
    state: absent

- name: gui-qtile | betterlockscreen | Verifica se instalado
  find:
    paths: "/usr/bin"
    patterns: 'betterlockscreen'
  register: betterlockscreen_instalado

# https://github.com/betterlockscreen/betterlockscreen
- name: gui-qtile | betterlockscreen | Instala pacote
  ansible.builtin.shell: |
    wget https://raw.githubusercontent.com/betterlockscreen/betterlockscreen/main/install.sh -O - -q | sudo bash -s system
  when: betterlockscreen_instalado.matched < 1

- name: gui-qtile | TWM | Instala demais pacotes que completam o ambiente
  ansible.builtin.dnf:
    name:
      - dmenu     # menu for X
      - rofi      # window switcher, application launcher and dmenu replacement
      - feh       # command line image viewer; wallpaper setter
      - gpick     # color picker
      - xrandr    # change output properties for an X screen
      - arandr    # GTK+ XRandR GUI
      - dunst     # notification-daemon
      - maim      # Command-line screen capture tool
      - picom     # Lightweight compositor for X11

- name: gui-qtile | ksuperkey | Dependências
  ansible.builtin.dnf:
    name:
      - git
      - gcc
      - make
      - libX11-devel
      - libXtst-devel
      - pkgconfig

- name: gui-qtile| ksuperkey | Cria diretório para clone de repositório
  ansible.builtin.file:
    path: "{{ usuario_home }}/Downloads/ksuperkey"
    state: directory
    mode: '0755'
  become_user: "{{ usuario }}"

- name: gui-qtile | ksuperkey | clone do repositório
  ansible.builtin.git:
    repo: 'https://github.com/hanschen/ksuperkey.git'
    dest: "{{ usuario_home }}/Downloads/ksuperkey"
  become_user: "{{ usuario }}"

- name: gui-qtile | Verifica se download realizado
  find:
    paths: "/usr/bin"
    patterns: 'ksuperkey'
  register: ksuperkey_instalado

- name: gui-qtile | ksuperkey | Instala
  ansible.builtin.shell: |
    cd /home/$SUDO_USER/Downloads/ksuperkey
    make
    make install
  when: ksuperkey_instalado.matched < 1

