- name: Copia arquivo de configuracoes do painel
  copy:
    src: panel-profile.tar.bz2
    dest: "{{ usuario_home }}/.local/share/xfce4-panel-profiles/panel-profile.tar.bz2"
    owner: "{{ usuario }}"
    group: "{{ usuario }}"
    mode: "0644"

- name: Define o painel
  become: yes
  become_user: "{{ usuario }}"
  command:
    cmd: xfce4-panel-profiles load "{{ usuario_home }}/.local/share/xfce4-panel-profiles/panel-profile.tar.bz2"
