- name: Copia arquivos de fontes
  copy:
    src: "{{ item }}"
    dest: "{{ usuario_home }}/Downloads/fontes/"
    owner: "{{ usuario }}"
    group: "{{ usuario }}"
    mode: "0644"
  loop:
    - fonts/NerdFontsSymbolsOnly.zip
    - fonts/BitstreamVeraSansMono.zip
    - fonts/FantasqueSansMono.zip
    - fonts/FiraCode.zip
    - fonts/Hack.zip
    - fonts/IBMPlexMono.zip
    - fonts/UbuntuMono.zip
    - fonts/VictorMono.zip
    - fonts/RobotoMono.zip
    - fonts/Cousine.zip
    - fonts/fonts.zip
    - fonts/JetBrainsMono.zip
    - fonts/Iosevka.zip

- name: Verifica existência de arquivos de fonte instalada
  stat:
    path: "/usr/share/fonts/Iosevka/"
  register: iosevka_present  

- name: Instalação de fontes
  shell: "unzip -o {{ usuario_home }}/Downloads/fontes/{{ item }} -d /usr/share/fonts/$(basename {{ item }} .zip)"
  loop: 
    - NerdFontsSymbolsOnly.zip
    - BitstreamVeraSansMono.zip
    - FantasqueSansMono.zip
    - FiraCode.zip
    - Hack.zip
    - IBMPlexMono.zip
    - UbuntuMono.zip
    - VictorMono.zip
    - RobotoMono.zip
    - Cousine.zip
    - fonts.zip
    - JetBrainsMono.zip
    - Iosevka.zip
  when: iosevka_present.stat.exists == false

- name: Verifica caminho - /comum/wallpapers
  stat:
    path: /comum/wallpapers/
  register: wallpapers_path

- name: Copia *wallpapers* (extrai arquivo .zip)
  ansible.builtin.unarchive:
    src: wallpapers/wallpapers.zip
    dest: /comum/wallpapers/
    owner: "{{ usuario }}"
    group: "{{ usuario }}"
    mode: "0644"
  when: wallpapers_path.stat.exists and wallpapers_path.stat.isdir
