- name: gui-xfce | xfconf | Garante existência do pacote
  dnf:
    name: xfconf
    state: present
  when: ansible_facts['distribution'] == "Fedora"

- name: gui-xfce | xfconf | Esconde ícones do desktop
  become_user: "{{ usuario }}"
  command:
    cmd: xfconf-query -c xfce4-desktop -p /desktop-icons/style --type int --set 0

- name: gui-xfce | gtk3.0 | Define CSS
  copy:
    src: themes/gtk.css
    dest: "{{ usuario_config }}/gtk-3.0/gtk.css"
    owner: "{{ usuario }}"
    group: "{{ usuario }}"
    mode: "0644"

- name: gui-xfce | xfce4-panel | Copia *profiles*
  copy:
    src: '{{item}}'
    dest: "{{ usuario_home }}/.local/share/xfce4-panel-profiles"
    owner: "{{ usuario }}"
    group: "{{ usuario }}"
    mode: "0644"
  loop:
    - panel-profile-solo-monitor.tar.bz2
    - panel-profile-dual-monitor.tar.bz2

- name: gui-xfce | Garante existência do pacote xrandr
  dnf:
    name: xrandr
    state: present

- name: gui-xfce | xfce4-panel | Define o *profile* conforme quantitativo de monitores
  become_user: "{{ usuario }}"
  shell: |
    if xrandr --listactivemonitors | grep -i monitors | awk '{print $2}' > 1; then
        xfce4-panel-profiles load "{{ usuario_home }}/.local/share/xfce4-panel-profiles/panel-profile-dual-monitor.tar.bz2"
    else
        xfce4-panel-profiles load "{{ usuario_home }}/.local/share/xfce4-panel-profiles/panel-profile-solo-monitor.tar.bz2"
    fi
  ignore_errors: false
  register: xfce4_panel_check
- debug:
    var: xfce4_panel_check.stdout

- name: gui-xfce | wallpapers | Script para definição no 'autostart' do ambiente
  copy:
    src: "{{ item }}"
    dest: "{{ usuario_config }}/autostart/"
    owner: "{{ usuario }}"
    mode: preserve
  with_fileglob:
    - "set-wallpaper/*"

- name: gui-xfce | Copia tema para janelas
  unarchive:
    src: themes/window/GTK-XFWM-Theme.zip
    dest: /usr/share/themes/

- name: gui-xfce | xfconf | Define tema para GTK (Appearance)
  become_user: "{{ usuario }}"
  command: "xfconf-query -c xsettings -p /Net/ThemeName -s Everblush"

- name: gui-xfce | xfconf | Define tema para Xfwm (Window Manager)
  become_user: "{{ usuario }}"
  command: "xfconf-query -c xfwm4 -p /general/theme -s Everblush-xfwm"

- name: gui-xfce | Copia tema para ícones
  unarchive:
    src: themes/icon/Nordzy-cyan-dark-MOD.zip
    dest: /usr/share/icons/

- name: gui-xfce | xfconf | Define tema dos ícones
  become_user: "{{ usuario }}"
  command: "xfconf-query -c xsettings -p /Net/IconThemeName -s Nordzy-cyan-dark-MOD"

- name: gui-xfce | Copia tema para cursor do mouse
  unarchive:
    src: themes/cursor/Bibata-Modern-Ice.tar.gz
    dest: /usr/share/icons/

- name: gui-xfce | xfconf | Define tema do cursor do mouse
  become_user: "{{ usuario }}"
  command: "xfconf-query -c xsettings -p /Gtk/CursorThemeName -s Bibata-Modern-Ice"

- name: gui-xfce | Define tema do cursor do mouse (default)
  lineinfile: 
    path: /usr/share/icons/default/index.theme
    search_string: 'Inherits='
    line: Inherits=Bibata-Modern-Ice

# https://github.com/AlexisBRENON/ewmh_m2m
# usado no atalho para movimentar janelas pelos monitores presentes
- name: gui-xfce | ewmh_m2m | Instalação do comando 'move-to-monitor'
  ansible.builtin.pip:
    name: ewmh-m2m    

- name: gui-xfce | xfce4-terminal | Configurações personalizadas
  become_user: "{{ usuario }}"
  copy:
    src: "{{ item }}"
    dest: "{{ usuario_config }}/xfce4/xfconf/xfce-perchannel-xml/"
    mode: "0644"
  with_items: 
    - xfce4-keyboard-shortcuts.xml
    - xfwm4.xml
    - xsettings.xml

- name: gui-xfce | Thunar actions | Configurações personalizadas
  become_user: "{{ usuario }}"
  copy:
    src: uca.xml
    dest: "{{ usuario_config }}/Thunar/uca.xml"
    mode: "0644"