## Copyright (C) 2020-2021 Aditya Shakya <adi1090x@gmail.com>
## Everyone is permitted to copy and distribute copies of this file under GNU-GPL3

# Font configuration
font:
  # Normal (roman) font face
  normal:
    family: "VictorMono Nerd Font"
    #family: "Iosevka Term"
    style: Medium

  # Bold font face
  bold:
    family: "VictorMono Nerd Font"
    style: Bold

  # Italic font face
  italic:
    family: "VictorMono Nerd Font"
    style: Italic

  # Bold italic font face
  bold_italic:
    family: "VictorMono Nerd Font"
    style: Bold Italic

  # Point size
  size: 10

  offset:
    x: 0
    y: 1
 

  # Offset
  #offset:
  #  x: 0
  #  y: 0

  # Glyph offset
  #glyph_offset:
  #  x: 0
  #  y: 0