# https://www.sublimetext.com/docs/linux_repositories.html
- name: gui-mix | Sublime | Importa chaves do repositório
  ansible.builtin.rpm_key:
    state: present
    key: https://download.sublimetext.com/sublimehq-rpm-pub.gpg
    
#- name: gui-mix | Sublime | Adiciona repositório 
#  ansible.builtin.dnf:
#    name: https://download.sublimetext.com/rpm/stable/x86_64/sublime-text.repo
#    state: present
#  when: ansible_facts['distribution'] == "Fedora"    

- name: gui-mix | Sublime | Adiciona repositório 
  yum_repository:
    name: sublime
    description: Sublime Text Editor Repository
    file: sublime
    baseurl: https://download.sublimetext.com/rpm/stable/x86_64
    state: present
    enabled: true
    gpgcheck: true
    gpgkey: https://download.sublimetext.com/sublimehq-rpm-pub.gpg
  when: ansible_facts['distribution'] == "Fedora"    

- name: gui-mix | Vivaldi | Importa chaves do repositório
  ansible.builtin.rpm_key:
    state: present
    key: https://repo.vivaldi.com/stable/linux_signing_key.pub

#- name: gui-mix | Vivaldi | Adiciona repositório 
#  ansible.builtin.dnf:
#    name: "https://repo.vivaldi.com/stable/vivaldi-fedora.repo"
#    state: present
#  when: ansible_facts['distribution'] == "Fedora"

- name: gui-mix | Vivaldi | Adiciona repositório 
  yum_repository:
    name: vivaldi
    description: Sublime Text Editor Repository
    file: sublime
    baseurl: https://repo.vivaldi.com/archive/rpm/x86_64
    state: present
    enabled: true
    gpgcheck: true
    gpgkey: https://repo.vivaldi.com/archive/linux_signing_key.pub
  when: ansible_facts['distribution'] == "Fedora"    

- name: gui-mix | Instala última versão de vários programas do ambiente gráfico
  ansible.builtin.dnf:
    name:
      # geany
      - geany-plugins-addons
      - geany-plugins-common
      - geany-plugins-markdown
      - geany-plugins-overview
      - geany-plugins-treebrowser
      - geany-themes
      - geany-plugins-autoclose
      - geany-plugins-automark
      - geany-plugins-geanyextrasel
      
      # editor
      - sublime-text
      - libreoffice
     
      # diff
      - meld
      
      # navegador
      - qutebrowser
      - vivaldi-stable
      
      # remote
      - remmina
      
      # net
      - wireshark

      # mix
      - copyq                           # clipboard manager (substitui 'xclipboard')
      - lightdm-gtk-greeter-settings    # Settings editor for LightDM GTK+ Greeter
      - foliate                         # GTK eBook reader
      - baobab                          # graphical directory tree analyzer
      - ulauncher                       # application launcher
      - qalculate-gtk                   # desktop calculator
      - xkill                           # force-close an X client's connection

- name: gui-mix | Sublime | Configuração presente?
  find:
    paths: "{{ usuario_config }}/sublime-text/Installed Packages/"
    patterns: '*.sublime-package'
  register: sublime_config
  
- name: gui-mix | Sublime | Define configuração padrão
  ansible.builtin.unarchive:
    src: sublime.tar.gz
    dest: "{{ usuario_config }}/sublime-text/"
  when: sublime_config.matched < 1

- name: gui-mix | lightdm-gtk-greeter | Define configuração padrão
  ansible.builtin.copy:
    src: lightdm-gtk-greeter.conf
    dest: /etc/lightdm/lightdm-gtk-greeter.conf
    mode: '0644'

- name: gui-mix | ulauncher/copyq | Define autostart
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ usuario_config }}/autostart/"
    mode: '0644'
    owner: "{{ usuario }}"
    group: "{{ usuario }}"
  loop:
    - /usr/share/applications/ulauncher.desktop
    - /usr/share/applications/com.github.hluk.copyq.desktop

- name: gui-mix | no autostart | Arquivos presentes?
  find:
    paths: "{{ usuario_config }}/autostart/"
    patterns: '*.desktop'
  register: no_autostart_config
  
- name: gui-mix | no autostart | Copia arquivos
  ansible.builtin.unarchive:
    src: no-autostart.tar.gz
    dest: "{{ usuario_config }}/autostart/"
  when: no_autostart_config.matched < 4


# outras instalações: AppImage, tarballs etc

- include_tasks: extra-gui-mix.yml