- name: Copia aliases, bashrc, zshrc, dircolors, fzf config
  copy:
    src: "{{ item }}"
    dest: "{{ usuario_home }}"
    owner: "{{ usuario }}"
    group: "{{ usuario }}"
    mode: preserve
  with_fileglob:  
    - "shell/.*"
    
- name: Copia starship.toml
  copy:
    src: shell/starship.toml
    dest: "{{ usuario_config }}"
    owner: "{{ usuario }}"
    group: "{{ usuario }}"
    mode: preserve
    
- name: Cria diretório para configurações do fzf
  file:
    path: "{{ usuario_home }}/.fzf/shell"
    state: directory
    owner: "{{ usuario }}" 
    group: "{{ usuario }}"
    mode: 0775

- name: Download bash/zsh completion e key-bindings para fzf
  become: yes
  become_user: "{{ usuario }}"
  ansible.builtin.get_url:
    url: "{{ item.link }}"
    dest: "{{ usuario_home }}/.fzf/shell/{{ item.file }}"
  loop:
    - { link: 'https://github.com/junegunn/fzf/raw/master/shell/completion.bash', file: 'completion.bash' }
    - { link: 'https://github.com/junegunn/fzf/raw/master/shell/completion.zsh', file: 'completion.zsh' }
    - { link: 'https://github.com/junegunn/fzf/raw/master/shell/key-bindings.bash', file: 'key-bindings.bash' }
    - { link: 'https://github.com/junegunn/fzf/raw/master/shell/key-bindings.zsh', file: 'key-bindings.zsh' }

- name: Cria '~/.config/ranger'
  file:
    path: "{{ usuario_config }}/ranger"
    state: directory
    owner: "{{ usuario }}" 
    group: "{{ usuario }}"
    mode: 0775

- name: Descompacta configurações de 'ranger'
  ansible.builtin.unarchive:
    src: ranger.tar.gz
    dest: "{{ usuario_config }}/ranger"
