# gping  - graph the ping time for multiple hosts
# trippy - like mtr, combines the functionality of traceroute and ping, supports multiple hosts
# bottom - graphical process/system monitor for the terminal
- name: Verifica se download de 'extras' já realizado
  find:
    paths: "{{ usuario_home }}/Downloads"
    patterns: 'gping*.tar.gz,trippy*.tar.gz,bottom*.tar.gz'
  register: find_matches

#- name: msg extra_download
#  debug: 
#    var: find_matches

- name: Download de binários pré-compilados
  become: yes
  become_user: "{{ usuario }}"
  ansible.builtin.shell: |
    curl -s https://api.github.com/repos/orf/gping/releases/latest \
      | grep browser_download_url \
      | grep Linux-x86_64 \
      | cut -d '"' -f 4 \
      | wget -P ~/Downloads -qi -
      
    curl -s https://api.github.com/repos/fujiapple852/trippy/releases/latest \
      | grep browser_download_url \
      | grep x86_64-unknown-linux-gnu.tar \
      | cut -d '"' -f 4 \
      | wget -P ~/Downloads -qi -    
    
    curl -s https://api.github.com/repos/ClementTsang/bottom/releases/latest \
      | grep browser_download_url \
      | grep x86_64-unknown-linux-gnu.tar \
      | cut -d '"' -f 4 \
      | wget -P ~/Downloads -qi -        
  when: find_matches.matched < 3

- name: Verifica se 'gping/bottom' já estão instalados
  find:
    paths: "{{ usuario_home }}/.local/bin"
    patterns: 'gping,btm'
  register: extra_instalado  
  
- name: Descompacta 'gping/bottom'
  ansible.builtin.unarchive:
    src: "{{ item }}"
    dest: "{{ usuario_home }}/.local/bin"
  with_fileglob:
    - "{{ usuario_home }}/Downloads/gping*.tar.gz"
    - "{{ usuario_home }}/Downloads/bottom*.tar.gz"
  when: extra_instalado.matched < 2

- name: Verifica se 'trippy' já instalado
  find:
    paths: "{{ usuario_home }}/.local/bin"
    patterns: 'trip'
  register: trippy_instalado    

- name: Descompacta 'trippy', evita criação de diretório dentro de '.local/bin'
  ansible.builtin.unarchive:
    src: "{{ item }}"
    dest: "{{ usuario_home }}/.local/bin"
    extra_opts:
      - "--strip-components=1"
    mode: '6755' # executar sempre como root
    owner: root
    group: root
  with_fileglob:
    - "{{ usuario_home }}/Downloads/trippy*.tar.gz"
  when: trippy_instalado.matched < 1