# gping  - graph the ping time for multiple hosts
# trippy - like mtr, combines the functionality of traceroute and ping, supports multiple hosts
# bottom - graphical process/system monitor for the terminal
# broot  - terminal file manager (https://dystroy.org/broot/) 
- name: extra_cli | extras | Verifica se download realizado
  find:
    paths: "{{ usuario_home }}/Downloads"
    patterns: 'gping*.tar.gz,trippy*.tar.gz,bottom*.tar.gz,broot*.zip'
  register: find_matches

#- name: msg extra_download
#  debug: 
#    var: find_matches

- name: extra_cli | Download de binários pré-compilados
  become: yes
  become_user: "{{ usuario }}"
  ansible.builtin.shell: |
    curl -s https://api.github.com/repos/orf/gping/releases/latest \
      | grep browser_download_url \
      | grep Linux-x86_64 \
      | cut -d '"' -f 4 \
      | wget -P ~/Downloads -qi -
      
    curl -s https://api.github.com/repos/fujiapple852/trippy/releases/latest \
      | grep browser_download_url \
      | grep x86_64-unknown-linux-gnu.tar \
      | cut -d '"' -f 4 \
      | wget -P ~/Downloads -qi -    
    
    curl -s https://api.github.com/repos/ClementTsang/bottom/releases/latest \
      | grep browser_download_url \
      | grep x86_64-unknown-linux-gnu.tar \
      | cut -d '"' -f 4 \
      | wget -P ~/Downloads -qi -        
    
    curl -s https://api.github.com/repos/Canop/broot/releases/latest \
      | grep browser_download_url \
      | cut -d '"' -f 4 \
      | wget -P ~/Downloads -qi -
  when: find_matches.matched < 4

- name: extra_cli | gping/btm | Verifica se instalados
  find:
    paths: "{{ usuario_home }}/.local/bin"
    patterns: 'gping,btm'
  register: extra_instalado  
  
- name: extra_cli | gping/btm | Descompacta 
  ansible.builtin.unarchive:
    src: "{{ item }}"
    dest: "{{ usuario_home }}/.local/bin"
  with_fileglob:
    - "{{ usuario_home }}/Downloads/gping*.tar.gz"
    - "{{ usuario_home }}/Downloads/bottom*.tar.gz"
  when: extra_instalado.matched < 2

- name: extra_cli | trippy | Verifica se instalado
  find:
    paths: "{{ usuario_home }}/.local/bin"
    patterns: 'trip'
  register: trippy_instalado    

- name: extra_cli | trippy | Descompacta
# evita criação de diretório dentro de '.local/bin'
  ansible.builtin.unarchive:
    src: "{{ item }}"
    dest: "{{ usuario_home }}/.local/bin"
    extra_opts:
      - "--strip-components=1"
    mode: '6755' # executar sempre como root
    owner: root
    group: root
  with_fileglob:
    - "{{ usuario_home }}/Downloads/trippy*.tar.gz"
  when: trippy_instalado.matched < 1
  
- name: extra_cli | broot | Verifica se instalado
  find:
    paths: "{{ usuario_home }}/.local/bin"
    patterns: 'broot'
  register: broot_instalado    
  
#- name: msg broot_instalado
#  debug: 
#    var: broot_instalado

- name: extra_cli | broot | Descompacta
# evita criação de diretório dentro de '.local/bin'
  ansible.builtin.command: unzip -j /home/$SUDO_USER/Downloads/broot*.zip x86_64-linux/broot -d /home/$SUDO_USER/.local/bin/
  when: broot_instalado.matched < 1
# nao foi possivel, com unarchive, extrair arquivo de 'x86_64-linux/broot' e,
# ao mesmo tempo nao criar subdiretorio no destino
# extra_opts: "-j" e "x86_64-linux/broot" nao trabalharam em conjunto

# nvchad (https://github.com/NvChad/NvChad)
- name: extra_cli | NvChad | git clone
  become: yes
  become_user: "{{ usuario }}"
  ansible.builtin.git:
    repo: 'https://github.com/NvChad/NvChad.git'
    dest: "{{ usuario_config }}/nvim"
    depth: 1

- name: extra_cli | NvChad | relative number
  ansible.builtin.lineinfile:
    path: "{{ usuario_config }}/nvim/lua/custom/init.lua"
    line: vim.opt.relativenumber = true
    
- name: extra_cli | NvChad | highlight focus line
  ansible.builtin.lineinfile:
    path: "{{ usuario_config }}/nvim/lua/custom/highlights.lua"
    insertafter: M.override
    line: '  CursorLine = { bg = "one_bg" },'
    
- name: extra_cli | NvChad | theme
  ansible.builtin.replace:
    path: "{{ usuario_config }}/nvim/lua/custom/chadrc.lua"
    regexp: onedark
    replace: oceanic-next
    
- name: extra_cli | bat | generate config file
  become: yes
  become_user: "{{ usuario }}"
  command: bat --generate-config-file

- name: extra_cli | bat | Verifica "{{ usuario_config }}/bat/themes"
  stat:
    path: "{{ usuario_config }}/bat/themes/"
  register: bat_themes_dir

- name: extra_cli | bat | Cria "{{ usuario_config }}/bat/themes"
  file:
    path: "{{ usuario_config }}/bat/themes/"
    state: directory
    mode: 0755
    group: "{{ usuario }}"
    owner: "{{ usuario }}"
  when: bat_themes_dir.stat.exists == false

- name: extra_cli | bat | Download temas Catppuccin
  become: yes
  become_user: "{{ usuario }}"
  ansible.builtin.get_url:
    url: "{{ item }}"
    dest: "{{ usuario_config }}/bat/themes/"
    mode: '0644'
  loop:
    - https://raw.githubusercontent.com/SublimeText/Spacegray/main/base16-eighties.dark.tmTheme
    - https://raw.githubusercontent.com/SublimeText/Spacegray/main/base16-mocha.dark.tmTheme
    - https://raw.githubusercontent.com/SublimeText/Spacegray/main/base16-ocean.dark.tmTheme
    - https://raw.githubusercontent.com/catppuccin/bat/main/Catppuccin-frappe.tmTheme
    - https://raw.githubusercontent.com/catppuccin/bat/main/Catppuccin-latte.tmTheme
    - https://raw.githubusercontent.com/catppuccin/bat/main/Catppuccin-macchiato.tmTheme
    - https://raw.githubusercontent.com/catppuccin/bat/main/Catppuccin-mocha.tmTheme            

- name: extra_cli | bat | reconstrução do cache
  become: yes
  become_user: "{{ usuario }}"
  command: bat cache --build
 
- name: extra_cli | bat | ajuste do arquivo de configurações
  ansible.builtin.lineinfile:
    path: "{{ usuario_config }}/bat/config"
    line: "{{item}}"
  loop:
    - '--theme="TwoDark"'
    - '--style="numbers,changes,header"' 
    - '--italic-text=always'

- name: extra_cli | rclone | Verifica "{{ usuario_home }}/virtual-drive"
  stat:
    path: "{{ usuario_home }}/virtual-drive"
  register: virtual_drive_dir
       
- name: extra_cli | rclone | Cria "{{ usuario_home }}/virtual-drive" e sub-diretórios
  file:
    path: "{{ usuario_home }}/virtual-drive/{{ item }}"
    state: directory
    recurse: yes
    mode: 0755
    group: "{{ usuario }}"
    owner: "{{ usuario }}"
  with_items: ["box","box-cache","dropbox","dropbox-cache","google-drive","google-drive-cache","mega","mega-cache","onedrive","onedrive-cache","ora-cloud","ora-cloud-cache",]
  when: virtual_drive_dir.stat.exists == false

- name: extra_cli | rclone | Download '.rclone.conf.gpg'
  become: yes
  become_user: "{{ usuario }}"
  ansible.builtin.get_url:
    url: https://github.com/victor-lyra/fedfiles/raw/main/.rclone.conf.gpg
    dest: "{{ usuario_home }}"
    mode: '0644'

- name: extra_cli | lesspass | Instalação
  ansible.builtin.pip:
    name: lesspass